### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by theLadyStardust** [YUNG-GANG/YUNGs-Better-Portals#3]
I tried adding Better Portals to my modpack I'm working on, and it crashes on loading a sp world. 
Logs: [crash-2021-02-09_08.20.31-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/5951927/crash-2021-02-09_08.20.31-server.txt)
I tried removing Nether Portal Fix, but the issue still happens. I'm on the latest version of forge for 1.16.4.

**Comment by yungnickyoung** [comment]
Looks like it's some sort of capability-related issue with the Shrink mod

**Comment by HonestAngel** [comment]
I have the same crash and if it is Shrink... I will just wait for it to be compatible. (Because the kids and I want shrink more...)
[crash-2021-02-23_08.33.26-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/6030438/crash-2021-02-23_08.33.26-server.txt)
[debug.log](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/6030442/debug.log)

Forge 36.0.42 and BetterPortals-1.16.4-0.3 (And too many mods to list sorry about that... blame my kids lol)

**Comment by yungnickyoung** [comment]
Try v0.3.1 to see if it fixes this issue for you.

**Comment by HonestAngel** [comment]
Thank you it seems to be working now. ^_^
