### ISSUE TITLE
Random worldgen crash

### ISSUE THREAD

**Issue by brisingraerowing** [YUNG-GANG/YUNGs-Better-Portals#7]
[Crash Log](https://gist.github.com/BrisingrAerowing/331fae12a332100d58e39f0ab928b523)

Randomly exploring and this happened. Completely froze the game and I had to kill the process.

**Comment by yungnickyoung** [comment]
Hey, please pastebin the log and link it here rather than uploading a file.

**Comment by brisingraerowing** [comment]
I added the log to the Gist.

**Comment by yungnickyoung** [comment]
Not sure what the issue is here but you have a _lot_ of errors going on. I'm talking 150+ FileNotFoundExceptions, a few IOExceptions, and a few NPEs. Also the crashlog (which shows an NPE for my mod) is completely different from the regular log in the gist. Not to mention the place where the null pointer occurs is around the World/Biome logic, which should always be passed in as a parameter to the function.

Dunno what's going on, but seems like your modded instance is potentially quite messed up.

**Comment by brisingraerowing** [comment]
I've removed some mods since, and haven't gotten the crash again (one of the mods added numerous structures, and it has some interesting issues).
